# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(180000)
$foreground = rgb(A6FAF3)
$color0 = rgb(180000)
$color1 = rgb(520501)
$color2 = rgb(9D0000)
$color3 = rgb(5E5D57)
$color4 = rgb(008201)
$color5 = rgb(BC9E00)
$color6 = rgb(00B5A7)
$color7 = rgb(77F0E6)
$color8 = rgb(53A8A1)
$color9 = rgb(6E0601)
$color10 = rgb(D10000)
$color11 = rgb(7D7C74)
$color12 = rgb(00AD02)
$color13 = rgb(FAD300)
$color14 = rgb(00F1DE)
$color15 = rgb(77F0E6)
