# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #A6FAF3
background         #180000
cursor             #BB7D7A

active_tab_foreground     #180000
active_tab_background     #A6FAF3
inactive_tab_foreground   #A6FAF3
inactive_tab_background   #180000

active_border_color   #A6FAF3
inactive_border_color #180000
bell_border_color     #520501

color0      #180000
color1		#520501
color2		#9D0000
color3		#5E5D57
color4		#008201
color5		#BC9E00
color6		#00B5A7
color7		#77F0E6
color8		#53A8A1
color9		#6E0601
color10		#D10000
color11		#7D7C74
color12		#00AD02
color13		#FAD300
color14		#00F1DE
color15		#77F0E6
